import { ArrowRight, ArrowUpRight, Compass, FileText, Landmark, Sparkles } from "lucide-react";
import { Link } from "wouter";
import SharedFooter from "@/components/SharedFooter";
import SharedNav from "@/components/SharedNav";

const resources = [
  { icon: Compass, label: "Start here", title: "The Readiness Map", body: "A free printable worksheet for naming one real job, setting a boundary, and choosing a next step without joining a program.", href: "/ReadinessMap", cta: "Get the free map", external: false },
  { icon: Landmark, label: "The member path", title: "The Watch", body: "Beacon’s annual member practice for people who want a steadier way to learn, organize useful work, and carry it forward.", href: "/the-watch", cta: "Review The Watch", external: false },
  { icon: FileText, label: "Public reading", title: "The Signal", body: "Source-led articles and field notes for people examining AI, work, and change without being sold a shortcut.", href: "/signal", cta: "Read The Signal", external: false },
  { icon: FileText, label: "A practical check", title: "A Claim Is Not Evidence", body: "A clear way to separate a product feature, a polished demonstration, a reported result, and a claim that still needs proof.", href: "/signal/a-claim-is-not-evidence", cta: "Read the article", external: false },
  { icon: FileText, label: "A practical check", title: "Can This Agent Do It—or May It Do It?", body: "A plain-language frame for deciding what an AI agent should be allowed to read, prepare, or pass to a person.", href: "/signal/can-this-agent-do-it-or-may-it-do-it", cta: "Read the article", external: false },
  { icon: Sparkles, label: "For organizations", title: "Beacon Labs", body: "A separate organization path for teams who need a practical, evidence-led way to assess a question and decide what to improve, test, defer, or leave alone.", href: "https://beaconlabs.ai", cta: "Visit Beacon Labs", external: true },
] as const;

function FieldLabel({ children, light = false }: { children: string; light?: boolean }) { return <p style={{ color: light ? "#D9B96D" : "#2E7A7D", fontFamily: "var(--beacon-mono)", fontSize: "0.68rem", fontWeight: 700, letterSpacing: "0.14em", margin: 0, textTransform: "uppercase" }}>{children}</p>; }

export default function ResourcesPage() {
  return <div data-resources-v3="true" style={{ background: "var(--beacon-parchment)", color: "var(--beacon-charcoal)", minHeight: "100vh" }}>
    <SharedNav />
    <main id="main-content">
      <section className="resources-hero"><img alt="An editorial desk with Beacon research materials" src="/images/owned/beacon-resources-editorial.png"/><div/><div className="container"><FieldLabel light>Public resources</FieldLabel><h1>Start with something useful.</h1><p>These resources are made to stand on their own. Read an article, use a worksheet, or take a practical idea into your work before you decide whether you need anything more.</p></div></section>
      <section className="resources-list"><div className="container"><div className="resources-heading"><div><FieldLabel>Choose what helps now</FieldLabel><h2>A library for clearer next steps.</h2></div><p>Public resources, The Watch, and Beacon Labs are different paths. Each one states what it is for before you continue.</p></div><div className="resources-grid">{resources.map((resource)=>{const Icon=resource.icon; const action=resource.external?<a href={resource.href} rel="noopener noreferrer" target="_blank">{resource.cta}<ArrowUpRight size={15}/></a>:<Link href={resource.href}>{resource.cta}<ArrowRight size={15}/></Link>; return <article key={resource.title}><Icon aria-hidden="true" size={21}/><p>{resource.label}</p><h3>{resource.title}</h3><span>{resource.body}</span>{action}</article>;})}</div></div></section>
      <section className="resources-boundary"><div className="container"><FieldLabel light>One clear boundary</FieldLabel><h2>A useful resource is not a hidden enrollment.</h2><p>The Readiness Map is a free resource. The Watch is an annual membership. Beacon Labs is a separate organization service. Choosing one does not create an account, a payment, or a record in another by default.</p><Link href="/how-beacon-works">See how Beacon works <ArrowRight size={16}/></Link></div></section>
    </main><SharedFooter />
    <style>{`
      [data-resources-v3="true"] .resources-hero { color: var(--beacon-parchment); min-height: 520px; overflow: hidden; padding: clamp(9rem,13vw,11rem) 0 4.5rem; position: relative; }[data-resources-v3="true"] .resources-hero img,[data-resources-v3="true"] .resources-hero > div:nth-child(2) { height: 100%; inset: 0; position: absolute; width: 100%; }[data-resources-v3="true"] .resources-hero img { object-fit: cover; object-position:center 40%; }[data-resources-v3="true"] .resources-hero > div:nth-child(2) { background: linear-gradient(90deg,rgba(22,36,51,.96),rgba(22,36,51,.74) 55%,rgba(22,36,51,.35)); }[data-resources-v3="true"] .resources-hero .container { max-width: 1050px; position: relative; }[data-resources-v3="true"] .resources-hero h1,[data-resources-v3="true"] h2 { font-size:clamp(2.6rem,5.8vw,6rem); line-height:.96; margin:1rem 0 0; }[data-resources-v3="true"] .resources-hero p { color:rgba(245,243,236,.79); font-size:1.08rem; line-height:1.78; margin:1.55rem 0 0; max-width:650px; }
      [data-resources-v3="true"] .resources-list { padding:clamp(4.5rem,9vw,8rem) 0; }[data-resources-v3="true"] .resources-heading { align-items:end; display:grid; gap:clamp(2rem,8vw,7rem); grid-template-columns:minmax(0,1fr) minmax(0,.78fr); margin-bottom:3rem; }[data-resources-v3="true"] .resources-heading > p { color:var(--beacon-charcoal-mid); font-size:.99rem; line-height:1.75; margin:0; }.resources-grid { display:grid; gap:1px; grid-template-columns:repeat(3,minmax(0,1fr)); }.resources-grid article { background:#fffaf2; border:1px solid var(--beacon-parchment-dark); display:flex; flex-direction:column; min-height:320px; padding:clamp(1.45rem,2.7vw,2rem); }.resources-grid article svg { color:var(--beacon-teal); }.resources-grid article > p { color:var(--beacon-teal); font-family:var(--beacon-mono); font-size:.63rem; font-weight:700; letter-spacing:.12em; margin:2rem 0 0; text-transform:uppercase; }.resources-grid h3 { font-size:1.65rem; margin:.7rem 0 0; }.resources-grid article > span { color:var(--beacon-charcoal-mid); font-size:.9rem; line-height:1.7; margin:.85rem 0 0; }.resources-grid a { align-items:center; color:var(--beacon-charcoal); display:inline-flex; font-family:var(--beacon-ui); font-size:.75rem; font-weight:800; gap:.45rem; letter-spacing:.05em; margin-top:auto; padding-top:1.5rem; text-decoration:underline; text-underline-offset:.25rem; text-transform:uppercase; }
      [data-resources-v3="true"] .resources-boundary { background:linear-gradient(125deg,#223345,#162433); color:var(--beacon-parchment); padding:clamp(4.5rem,9vw,7.5rem) 0; }[data-resources-v3="true"] .resources-boundary .container { max-width:1100px; }[data-resources-v3="true"] .resources-boundary h2 { margin-top:1rem; max-width:780px; }[data-resources-v3="true"] .resources-boundary p { color:rgba(245,243,236,.77); font-size:1.04rem; line-height:1.75; margin:1.35rem 0 0; max-width:690px; }[data-resources-v3="true"] .resources-boundary a { align-items:center; color:var(--beacon-amber-light); display:inline-flex; font-family:var(--beacon-ui); font-size:.78rem; font-weight:800; gap:.45rem; letter-spacing:.06em; margin-top:1.7rem; text-decoration:underline; text-underline-offset:.25rem; text-transform:uppercase; }
      @media(max-width:820px){[data-resources-v3="true"] .resources-heading,.resources-grid{grid-template-columns:1fr;}}
    `}</style>
  </div>;
}
